spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutor_app
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  autoconfigure:
    exclude: #
#    main:
#      web-application-type: none # disables web server
#      lazy-initialization: true # Initializes objects when they need

  profiles: # dev, prod yaml's
    active: dev # dev, prod comma seperated value
#    SETUP BASE URL PATH
#  data:
#    rest: #  Works spring version < 2.0
#      base-path: /api/v1 # Refer Docs https://stackoverflow.com/questions/47462267/setting-spring-rest-controllers-base-url-without-changing-the-static-resources-b/47466349
management:
  endpoints:
    web:
      exposure:
        include: "*"
# To set up entire application including MVC template
server:
  servlet:
    context-path: /api/v1 # Works spring version > 2.0
# BASE PATH SETUP END
#  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
json_placeholder:
  base_url: https://jsonplaceholder.typicode.com

developer:
  mode: ${spring.profiles.active}
  name: dinesh